# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: 2023 Tristan Partin <tristan@partin.io>

name: Builds

on:
  release:
    types: [created]
  push:
    branches:
      - master
      - "v[0-9]+.[0-9]+"
    paths:
      - "**.c"
      - "**.h"
      - "**/meson.build"
      - .github/workflows/builds.yaml
      - meson_options.txt
      - VERSION
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**.c"
      - "**.h"
      - "**/meson.build"
      - .github/workflows/builds.yaml
      - meson_options.txt
      - VERSION

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  normal:
    runs-on: ubuntu-latest
    container: quay.io/fedora/fedora:38
    strategy:
      fail-fast: true
      matrix:
        buildtype: [debug, release]
        plain: [enabled, disabled]

    steps:
      - name: Install dependencies
        run: |
          dnf install --assumeyes --setopt=install_weak_deps=False \
            gcc meson glib2-devel

      - name: Checkout libmerr
        uses: actions/checkout@v5

      - name: Setup
        run: |
          meson setup build --fatal-meson-warnings --werror \
            --buildtype=${{ matrix.buildtype }} -Dplain=${{ matrix.plain }}

      - name: Build
        run: |
          ninja -C build

      - name: Test
        run: |
          meson test -C build --print-errorlogs --no-stdsplit

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.buildtype }}-plain-${{ matrix.plain }}
          path: |
            build/meson-logs/

  asan-ubsan:
    runs-on: ubuntu-latest
    container: quay.io/fedora/fedora:38
    strategy:
      fail-fast: true
      matrix:
        buildtype: [debug, release]
        plain: [enabled, disabled]

    steps:
      - name: Install dependencies
        run: |
          dnf install --assumeyes --setopt=install_weak_deps=False \
            gcc meson glib2-devel libasan libubsan

      - name: Checkout libmerr
        uses: actions/checkout@v5

      - name: Setup
        run: |
          meson setup build --fatal-meson-warnings --werror \
            --buildtype=${{ matrix.buildtype }} -Db_sanitize=address,undefined \
            -Dplain=${{ matrix.plain }}

      - name: Build
        run: |
          ninja -C build

      - name: Test
        run: |
          meson test -C build --print-errorlogs --no-stdsplit

      - name: Upload artifacts
        uses: actions/upload-artifact@v5
        if: failure()
        with:
          name: ${{ github.job }}-${{ matrix.buildtype }}-plain-${{ matrix.plain }}
          path: |
            build/meson-logs/
