# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: 2023 Tristan Partin <tristan@partin.io>

name: markdownlint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - README.md

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout libmerr
        uses: actions/checkout@v7

      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Nix store
        uses: DeterminateSystems/magic-nix-cache-action@v15

      - name: markdownlint check
        run: |
          nix develop --command markdownlint-cli2 \
            README.md
