# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: 2023 Tristan Partin <tristan@partin.io>

name: markdownlint

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - README.md

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  markdownlint:
    runs-on: ubuntu-latest

    steps:
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: npm

      - name: Checkout libmerr
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          npm ci

      - name: markdownlint check
        run: |
          npm run markdownlint:check
