# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# SPDX-FileCopyrightText: 2023 Tristan Partin <tristan@partin.io>

name: REUSE

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  reuse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout libmerr
        uses: actions/checkout@v4

      - name: Lint
        uses: fsfe/reuse-action@v4
        with:
          args: --include-meson-subprojects lint
